/**
 * Express/Node.js-specific installer
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'node:url';
import type { InstallOptions, Environment } from '../cli.js';
import { generateAdapters } from '../generators/generate-adapters.js';
import { generateEndpoint } from '../generators/generate-endpoint.js';
import { generateBindings } from '../generators/generate-bindings.js';
import { generateMigrations } from '../generators/generate-migrations.js';

export interface InstallResult {
  kernelId: string;
  integration: string;
}

export async function installExpress(options: InstallOptions & { env?: Environment }): Promise<InstallResult> {
  const cwd = process.cwd();
  const env = options.env || 'development';
  const controlPlaneDir = path.join(cwd, 'control_plane');
  
  // Environment-aware defaults
  const kernelId = options.kernelId || (env === 'development' 
    ? `express-dev-${Date.now()}`
    : env === 'staging'
    ? `express-staging-${Date.now()}`
    : 'express-kernel');
  
  const integration = options.integration || (env === 'development'
    ? 'express-dev'
    : 'express');

  console.log(`📁 Installing to: ${controlPlaneDir}\n`);

  // Step 1: Copy TypeScript kernel
  console.log('📦 Copying TypeScript kernel...');
  await copyKernel(controlPlaneDir, 'typescript');
  console.log('✅ Kernel copied\n');

  // Step 2: Generate adapters
  console.log('🔧 Generating adapters...');
  await generateAdapters({
    framework: 'express',
    outputDir: controlPlaneDir,
    integration,
  });
  console.log('✅ Adapters generated\n');

  // Step 3: Generate bindings
  console.log('⚙️  Generating bindings...');
  await generateBindings({
    framework: 'express',
    outputDir: cwd,
    integration,
    kernelId,
  });
  console.log('✅ Bindings generated\n');

  // Step 4: Generate /api/manage endpoint
  console.log('🌐 Generating /api/manage endpoint...');
  await generateEndpoint({
    framework: 'express',
    outputDir: cwd,
    integration,
    kernelId,
  });
  console.log('✅ Endpoint generated\n');

  // Step 5: Generate migrations
  console.log('🗄️  Generating database migrations...');
  const migrationFiles = await generateMigrations({
    framework: 'express',
    outputDir: cwd,
  });
  console.log(`✅ Migrations generated: ${migrationFiles.join(', ')}\n`);

  // Step 6: Update package.json dependencies
  console.log('📦 Updating package.json...');
  await updatePackageJson(cwd);
  console.log('✅ Package.json updated\n');

  // Step 7: Create .env.example
  console.log('📝 Creating environment variable template...');
  await createEnvExample(cwd, kernelId, integration, options, env);
  console.log('✅ Environment template created\n');

  return { kernelId, integration };
}

async function copyKernel(targetDir: string, kernelType: 'typescript' | 'python'): Promise<void> {
  const installerDir = path.dirname(fileURLToPath(import.meta.url));
  const repoRoot = path.resolve(installerDir, '../..');
  
  const kernelSource = path.join(repoRoot, 'kernel', 'src');
  const kernelTarget = path.join(targetDir, 'kernel', 'src');
  
  fs.mkdirSync(kernelTarget, { recursive: true });
  copyDirectory(kernelSource, kernelTarget);
}

function copyDirectory(src: string, dest: string): void {
  if (!fs.existsSync(src)) {
    throw new Error(`Source directory does not exist: ${src}`);
  }
  
  fs.mkdirSync(dest, { recursive: true });
  
  const entries = fs.readdirSync(src, { withFileTypes: true });
  
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    
    if (entry.isDirectory()) {
      copyDirectory(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

async function updatePackageJson(cwd: string): Promise<void> {
  const packageJsonPath = path.join(cwd, 'package.json');
  if (!fs.existsSync(packageJsonPath)) {
    console.warn('⚠️  package.json not found. Skipping dependency update.');
    return;
  }

  const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
  
  // Add dependencies if not present
  pkg.dependencies = pkg.dependencies || {};
  if (!pkg.dependencies['@supabase/supabase-js']) {
    pkg.dependencies['@supabase/supabase-js'] = '^2.0.0';
  }

  fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n');
}

async function createEnvExample(cwd: string, kernelId: string, integration: string, options: InstallOptions, env: Environment): Promise<void> {
  const isDev = env === 'development';
  
  const envExample = `# Agentic Control Plane Configuration
# Generated by Echelon installer
# Environment: ${env.toUpperCase()}

# Kernel Identity
KERNEL_ID=${kernelId}
INTEGRATION=${integration}

${isDev ? `# Development Mode: Optional connections (safe to skip)
# Governance Hub (Repo B) - Optional in dev
# GOVERNANCE_HUB_URL=https://dev-governance-hub.supabase.co
# ACP_KERNEL_KEY=acp_kernel_dev_xxxxx

# Key Vault Executor (Repo C) - Optional in dev
# CIA_URL=https://dev-vault.supabase.co
# CIA_SERVICE_KEY=cia_service_dev_xxxxx
# CIA_ANON_KEY=eyJ...
` : `# Governance Hub (Repo B)
GOVERNANCE_HUB_URL=${options.governanceHubUrl || 'https://xxx.supabase.co'}
ACP_KERNEL_KEY=${options.kernelApiKey || 'acp_kernel_xxxxx'}

# Key Vault Executor (Repo C)
CIA_URL=${options.ciaUrl || 'https://yyy.supabase.co'}
CIA_SERVICE_KEY=${options.ciaServiceKey || 'cia_service_xxxxx'}
CIA_ANON_KEY=${options.ciaAnonKey || 'eyJ...'}
`}
`;

  const envPath = path.join(cwd, '.env.example');
  fs.writeFileSync(envPath, envExample);
}
