/**
 * Generate framework-specific adapters
 *
 * Creates adapter implementations for the detected framework.
 */

import * as fs from 'fs';
import * as path from 'path';
import { getAgenticKitPackageRoot } from '../kit-root.js';

export interface AdapterGenerationOptions {
  framework: 'django' | 'express' | 'supabase' | 'hybrid_netlify_supabase';
  outputDir: string;
  integration: string;
}

export async function generateAdapters(options: AdapterGenerationOptions): Promise<void> {
  const { framework, outputDir, integration } = options;

  switch (framework) {
    case 'django':
      await generateDjangoAdapters(outputDir, integration);
      break;
    case 'express':
    case 'hybrid_netlify_supabase':
      await generateExpressAdapters(outputDir, integration, framework === 'hybrid_netlify_supabase');
      break;
    case 'supabase':
      await generateSupabaseAdapters(outputDir, integration);
      break;
  }
}

async function generateDjangoAdapters(outputDir: string, integration: string): Promise<void> {
  const adaptersDir = path.join(outputDir, 'adapters');
  fs.mkdirSync(adaptersDir, { recursive: true });

  const adaptersPy = `"""
Framework adapters for Django
Generated by Echelon installer
"""

from control_plane.acp.types import (
    DbAdapter, AuditAdapter, IdempotencyAdapter,
    RateLimitAdapter, CeilingsAdapter
)
from django.db import connection, ProgrammingError
from django.core.cache import cache

# Customize: import your models and wire real persistence for production.
# from myapp.models import ApiKey, Tenant, AuditLog

class DjangoDbAdapter(DbAdapter):
    """Database adapter using Django ORM"""

    async def query(self, sql, params=None):
        with connection.cursor() as cursor:
            cursor.execute(sql, params or [])
            columns = [col[0] for col in cursor.description]
            return [dict(zip(columns, row)) for row in cursor.fetchall()]

    async def get_tenant_from_api_key(self, api_key_id):
        try:
            with connection.cursor() as cursor:
                cursor.execute(
                    "SELECT tenant_id FROM api_keys WHERE id = %s LIMIT 1",
                    [api_key_id],
                )
                row = cursor.fetchone()
                return str(row[0]) if row else None
        except ProgrammingError:
            # Missing table/column (e.g. migrations not applied) — treat as unknown key.
            return None

class DjangoAuditAdapter(AuditAdapter):
    """Audit adapter — default no-op until you persist audit_log rows."""

    async def log(self, entry):
        pass

class DjangoIdempotencyAdapter(IdempotencyAdapter):
    """Idempotency using Django cache"""

    async def get_replay(self, tenant_id, action, idempotency_key):
        key = f"idempotency:{tenant_id}:{action}:{idempotency_key}"
        return cache.get(key)

    async def store_replay(self, tenant_id, action, idempotency_key, response):
        key = f"idempotency:{tenant_id}:{action}:{idempotency_key}"
        cache.set(key, response, timeout=86400)  # 24 hours

class DjangoRateLimitAdapter(RateLimitAdapter):
    """Rate limiting using Django cache"""

    async def check(self, api_key_id, action, limit):
        key = f"ratelimit:{api_key_id}:{action}"
        count = cache.get(key, 0)
        allowed = count < limit
        if allowed:
            cache.set(key, count + 1, timeout=60)
        return {'allowed': allowed, 'limit': limit, 'remaining': max(0, limit - count - 1)}

class DjangoCeilingsAdapter(CeilingsAdapter):
    """Ceilings — permissive defaults; enforce real limits in production."""

    async def check(self, action, params, tenant_id):
        return None

    async def get_usage(self, ceiling_name, tenant_id, period=None):
        return 0
`;

  fs.writeFileSync(path.join(adaptersDir, '__init__.py'), adaptersPy);
}

async function generateExpressAdapters(
  outputDir: string,
  integration: string,
  hybridNetlifySupabase = false,
): Promise<void> {
  const adaptersDir = path.join(outputDir, 'adapters');
  fs.mkdirSync(adaptersDir, { recursive: true });

  const label = hybridNetlifySupabase
    ? 'Netlify Functions (hybrid) + Supabase data plane'
    : 'Express/Node.js';

  const adaptersTs = `/**
 * Framework adapters for ${label}
 * Generated by Echelon installer
 *
 * ECHELON_ADAPTER_SURFACE: bootstrap_in_memory — in-process DevDefault* adapters (TGA-194).
 * They throw in NODE_ENV=production unless ECHELON_ADAPTER_PROFILE=bootstrap or ECHELON_ALLOW_BOOTSTRAP_ADAPTERS=1.
 * Replace with durable persistence before production.
 */

import {
  DevDefaultDbAdapter,
  DevDefaultAuditAdapter,
  DevDefaultIdempotencyAdapter,
  DevDefaultRateLimitAdapter,
  DevDefaultCeilingsAdapter,
} from '../kernel/src/dev-default-adapters';
import { guardEchelonBootstrapAdapters } from '../kernel/src/echelon-bootstrap-adapter-guard';

export const ECHELON_ADAPTER_SURFACE = 'bootstrap_in_memory' as const;

export class ExpressDbAdapter extends DevDefaultDbAdapter {
  constructor() {
    super();
    guardEchelonBootstrapAdapters('ExpressDbAdapter');
  }
}

export class ExpressAuditAdapter extends DevDefaultAuditAdapter {
  constructor() {
    super();
    guardEchelonBootstrapAdapters('ExpressAuditAdapter');
  }
}

export class ExpressIdempotencyAdapter extends DevDefaultIdempotencyAdapter {
  constructor() {
    super();
    guardEchelonBootstrapAdapters('ExpressIdempotencyAdapter');
  }
}

export class ExpressRateLimitAdapter extends DevDefaultRateLimitAdapter {
  constructor() {
    super();
    guardEchelonBootstrapAdapters('ExpressRateLimitAdapter');
  }
}

export class ExpressCeilingsAdapter extends DevDefaultCeilingsAdapter {
  constructor() {
    super();
    guardEchelonBootstrapAdapters('ExpressCeilingsAdapter');
  }
}

export function createAdapters() {
  return {
    dbAdapter: new ExpressDbAdapter(),
    auditAdapter: new ExpressAuditAdapter(),
    idempotencyAdapter: new ExpressIdempotencyAdapter(),
    rateLimitAdapter: new ExpressRateLimitAdapter(),
    ceilingsAdapter: new ExpressCeilingsAdapter(),
  };
}
`;

  fs.writeFileSync(path.join(adaptersDir, 'index.ts'), adaptersTs);
}

async function generateSupabaseAdapters(outputDir: string, integration: string): Promise<void> {
  const adaptersDir = path.join(outputDir, 'adapters');
  fs.mkdirSync(adaptersDir, { recursive: true });
  const root = getAgenticKitPackageRoot();
  const tplPath = path.join(root, 'installer', 'templates', 'supabase-deno-adapters.index.ts');
  const content = fs.readFileSync(tplPath, 'utf-8');
  fs.writeFileSync(path.join(adaptersDir, 'index.ts'), content);
}
