/**
 * Generate framework-specific adapters
 *
 * Creates adapter implementations for the detected framework.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface AdapterGenerationOptions {
  framework: 'django' | 'express' | 'supabase' | 'hybrid_netlify_supabase';
  outputDir: string;
  integration: string;
}

export async function generateAdapters(options: AdapterGenerationOptions): Promise<void> {
  const { framework, outputDir, integration } = options;

  switch (framework) {
    case 'django':
      await generateDjangoAdapters(outputDir, integration);
      break;
    case 'express':
    case 'hybrid_netlify_supabase':
      await generateExpressAdapters(outputDir, integration, framework === 'hybrid_netlify_supabase');
      break;
    case 'supabase':
      await generateSupabaseAdapters(outputDir, integration);
      break;
  }
}

async function generateDjangoAdapters(outputDir: string, integration: string): Promise<void> {
  const adaptersDir = path.join(outputDir, 'adapters');
  fs.mkdirSync(adaptersDir, { recursive: true });

  const adaptersPy = `"""
Framework adapters for Django
Generated by Echelon installer
"""

from control_plane.acp.types import (
    DbAdapter, AuditAdapter, IdempotencyAdapter,
    RateLimitAdapter, CeilingsAdapter
)
from django.db import connection
from django.core.cache import cache

# Customize: import your models and wire real persistence for production.
# from myapp.models import ApiKey, Tenant, AuditLog

class DjangoDbAdapter(DbAdapter):
    """Database adapter using Django ORM"""

    async def query(self, sql, params=None):
        with connection.cursor() as cursor:
            cursor.execute(sql, params or [])
            columns = [col[0] for col in cursor.description]
            return [dict(zip(columns, row)) for row in cursor.fetchall()]

    async def get_tenant_from_api_key(self, api_key_id):
        try:
            with connection.cursor() as cursor:
                cursor.execute(
                    "SELECT tenant_id FROM api_keys WHERE id = %s LIMIT 1",
                    [api_key_id],
                )
                row = cursor.fetchone()
                return str(row[0]) if row else None
        except Exception:
            return None

class DjangoAuditAdapter(AuditAdapter):
    """Audit adapter — default no-op until you persist audit_log rows."""

    async def log(self, entry):
        pass

class DjangoIdempotencyAdapter(IdempotencyAdapter):
    """Idempotency using Django cache"""

    async def get_replay(self, tenant_id, action, idempotency_key):
        key = f"idempotency:{tenant_id}:{action}:{idempotency_key}"
        return cache.get(key)

    async def store_replay(self, tenant_id, action, idempotency_key, response):
        key = f"idempotency:{tenant_id}:{action}:{idempotency_key}"
        cache.set(key, response, timeout=86400)  # 24 hours

class DjangoRateLimitAdapter(RateLimitAdapter):
    """Rate limiting using Django cache"""

    async def check(self, api_key_id, action, limit):
        key = f"ratelimit:{api_key_id}:{action}"
        count = cache.get(key, 0)
        allowed = count < limit
        if allowed:
            cache.set(key, count + 1, timeout=60)
        return {'allowed': allowed, 'limit': limit, 'remaining': max(0, limit - count - 1)}

class DjangoCeilingsAdapter(CeilingsAdapter):
    """Ceilings — permissive defaults; enforce real limits in production."""

    async def check(self, action, params, tenant_id):
        return None

    async def get_usage(self, ceiling_name, tenant_id, period=None):
        return 0
`;

  fs.writeFileSync(path.join(adaptersDir, '__init__.py'), adaptersPy);
}

async function generateExpressAdapters(
  outputDir: string,
  integration: string,
  hybridNetlifySupabase = false,
): Promise<void> {
  const adaptersDir = path.join(outputDir, 'adapters');
  fs.mkdirSync(adaptersDir, { recursive: true });

  const label = hybridNetlifySupabase
    ? 'Netlify Functions (hybrid) + Supabase data plane'
    : 'Express/Node.js';

  const adaptersTs = `/**
 * Framework adapters for ${label}
 * Generated by Echelon installer
 *
 * Defaults are in-memory dev implementations from the kernel (runnable smoke tests).
 * Replace with your database client (Prisma, Drizzle, Supabase, etc.) before production.
 */

export {
  DevDefaultDbAdapter as ExpressDbAdapter,
  DevDefaultAuditAdapter as ExpressAuditAdapter,
  DevDefaultIdempotencyAdapter as ExpressIdempotencyAdapter,
  DevDefaultRateLimitAdapter as ExpressRateLimitAdapter,
  DevDefaultCeilingsAdapter as ExpressCeilingsAdapter,
} from '../kernel/src/dev-default-adapters';
`;

  fs.writeFileSync(path.join(adaptersDir, 'index.ts'), adaptersTs);
}

async function generateSupabaseAdapters(outputDir: string, integration: string): Promise<void> {
  const adaptersDir = path.join(outputDir, 'adapters');
  fs.mkdirSync(adaptersDir, { recursive: true });

  const adaptersTs = `/**
 * Framework adapters for Supabase (Deno / Edge)
 * Generated by Echelon installer
 *
 * Defaults are in-memory dev implementations from the kernel (runnable smoke tests).
 * Wire createClient + PostgREST/RPC for production persistence.
 */

export {
  DevDefaultDbAdapter as SupabaseDbAdapter,
  DevDefaultAuditAdapter as SupabaseAuditAdapter,
  DevDefaultIdempotencyAdapter as SupabaseIdempotencyAdapter,
  DevDefaultRateLimitAdapter as SupabaseRateLimitAdapter,
  DevDefaultCeilingsAdapter as SupabaseCeilingsAdapter,
} from '../kernel/src/dev-default-adapters';
`;

  fs.writeFileSync(path.join(adaptersDir, 'index.ts'), adaptersTs);
}
