/**
 * Generate bindings configuration file
 */

import * as fs from 'fs';
import * as path from 'path';

export interface BindingsGenerationOptions {
  framework: 'django' | 'express' | 'supabase';
  outputDir: string;
  integration: string;
  kernelId: string;
  basePath?: string;  // Base path for endpoint (default: /api/manage)
  tenantTable?: string;
  apiKeyTable?: string;
  apiKeyPrefix?: string;
}

export async function generateBindings(options: BindingsGenerationOptions): Promise<string> {
  const { framework, outputDir, integration, kernelId, basePath, tenantTable, apiKeyTable, apiKeyPrefix } = options;

  const bindings = {
    kernelId,
    integration,
    base_path: basePath || '/api/manage',  // Include base path in bindings
    endpoint_path: basePath || '/api/manage',  // Full endpoint path
    tenant: {
      table: tenantTable || 'tenants',
      id_column: 'id',
    },
    auth: {
      keys_table: apiKeyTable || 'api_keys',
      key_prefix: apiKeyPrefix || `${integration.substring(0, 3)}k_`,
      prefix_length: 12,
    },
    database: {
      adapter: framework === 'django' ? 'django' : framework === 'supabase' ? 'supabase' : 'prisma',
    },
  };

  // For Django, generate Python bindings.py
  if (framework === 'django') {
    const bindingsPy = `"""
Bindings configuration
Generated by Echelon installer
"""

import os

def get_bindings():
    return {
        'kernelId': os.environ.get('KERNEL_ID', '${kernelId}'),
        'integration': '${integration}',
        'base_path': '${bindings.base_path}',
        'endpoint_path': '${bindings.endpoint_path}',
        'tenant': {
            'table': '${bindings.tenant.table}',
            'id_column': '${bindings.tenant.id_column}',
        },
        'auth': {
            'keys_table': '${bindings.auth.keys_table}',
            'key_prefix': '${bindings.auth.key_prefix}',
            'prefix_length': ${bindings.auth.prefix_length},
        },
        'database': {
            'adapter': '${bindings.database.adapter}',
        },
    }
`;

    const filePath = path.join(outputDir, 'control_plane', 'bindings.py');
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, bindingsPy);
    return filePath;
  }

  // For Express/Supabase, generate JSON bindings
  const filePath = path.join(outputDir, 'controlplane.bindings.json');
  fs.writeFileSync(filePath, JSON.stringify(bindings, null, 2));
  return filePath;
}
